#!/usr/bin/env python3

import sys
from itertools import product

answers = {
  'about',
  'after',
  'again',
  'below',
  'could',
  'every',
  'first',
  'found',
  'great',
  'house',
  'large',
  'learn',
  'never',
  'other',
  'place',
  'plant',
  'point',
  'right',
  'small',
  'sound',
  'spell',
  'still',
  'study',
  'their',
  'there',
  'these',
  'thing',
  'think',
  'three',
  'water',
  'where',
  'which',
  'world',
  'would',
  'write',
}

lines = [chars.strip() for chars in sys.stdin]
print(next(password for password in map(''.join, product(*lines))
           if password in answers))
