#!/usr/bin/env python3

from utils import yesno
from utils import num
from utils import coded_colors

if yesno('Serial number contains a vowel'):
  button_mapping = {
    0: {
      'red': 'blue',
      'blue': 'red',
      'green': 'yellow',
      'yellow': 'green',
    },
    1: {
      'red': 'yellow',
      'blue': 'green',
      'green': 'blue',
      'yellow': 'red',
    },
    2: {
      'red': 'green',
      'blue': 'red',
      'green': 'yellow',
      'yellow': 'blue',
    },
  }
else:
  button_mapping = {
    0: {
      'red': 'blue',
      'blue': 'yellow',
      'green': 'green',
      'yellow': 'red',
    },
    1: {
      'red': 'red',
      'blue': 'blue',
      'green': 'yellow',
      'yellow': 'green',
    },
    2: {
      'red': 'yellow',
      'blue': 'green',
      'green': 'blue',
      'yellow': 'red',
    },
  }

num_strikes = num('strikes')

button_seq = []

while True:
  try:
    color_code = input('Color of new flashing button: ')
  except EOFError:
    break
  if not color_code:
    break
  button_seq.append(button_mapping[num_strikes][coded_colors[color_code]])
  print(f'Press in sequence {button_seq}.')
